data = {
    "tasks": [
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Я … человек.\n\n1) добро\n2) доброта\n3) добрая\n4) добрый",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я хочу поехать в Россию и тоже изучать ... .\n\n1) по-русски\n2) немецкий\n3) русский язык\n4) русские",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Меня ... Антон.\n\n1) фамилия\n2) зовут\n3) имя\n4) отец.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Мой родной ... - испанский.\n\n1) страна\n2) язык\n3) город\n4) народ.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Мое любимое время года - … .\n\n1) лето\n2) летом\n3) летний\n4) летние",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Мой друг очень хорошо говорит ... .\n\n1) по-русски\n2) русский\n3) русский язык\n4) русские.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Моя мама хорошо … суп.\n\n1) говорит\n2) готовит\n3) играет\n4) пишет",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Папа часто … газету вечером.\n\n1) читает\n2) слушает\n3) ест\n4) смотрит",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мой друг ... в Москве.\n\n1) жить\n2) живёт\n3) живу\n4) живёте.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Сейчас зима, на улице … .\n\n1) тепло\n2) холодно\n3) жарко\n4) весело.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Михаил Николаевич - ... учитель.\n\n1) школа\n2) школьник\n3) школьница\n4) школьный.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Мой учитель говорит, что ...  - его второй дом.\n\n1) школа\n2) школьник\n3) школьница\n4) школьный.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "На столе лежит … .\n\n1) ручка\n2) ручки\n3) ручек\n4) ручку.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Я очень люблю … музыку.\n\n1) слушать\n2) пить\n3) читать\n4) готовить.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "По вечерам я ... телевизор.\n\n1) смотрю\n2) вижу\n3) читаю\n4) слушаю.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Самара -  … город на Волге.\n\n1) это\n2) этот\n3) эта\n4) эти.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Покажите … город на карте.\n\n1) это\n2) этот\n3) эта\n4) эти.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "У меня … книги.\n\n1) нет\n2) не.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "У меня нет … .\n\n1) книга\n2) книг\n3) книгу\n4) книгах.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "У него … машина.\n\n1) новый\n2) новая\n3) новые\n4) новое.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "… , где вокзал?\n\n1) Извините\n2) Извинитесь\n3) Извини\n4) Извиняю.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Мне, …, чай.\n\n1) Простите\n2) Благодарю\n3) Пожалуйста\n4) Спасибо.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Grammar",
            "task_content": "Я люблю ... в футбол.\n\n1) бегать\n2) играть\n3) гулять\n4) смотреть",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 2,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я люблю отдыхать … на море.\n\n1) лето\n2) летом\n3) летний\n4) летние",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я  не знаю твой ...  телефон.\n\n1) дом\n2) дома\n3) домой\n4) домашний.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мы родились и выросли в Москве. Москва - это …  город.\n\n1) наш\n2) наша\n3) наше\n4) наши.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Это … брат.\n\n1) мой\n2) моя\n3) моё\n4) мои.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мои друзья ...  в университете.\n\n1) учатся\n2) учат\n3) занимаются\n4) изучают.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мы с друзьями ... кино.\n\n1) любим\n2) любить\n3) любит\n4) любите.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мой друг ... в Москве.\n\n1) жить\n2) живёт\n3) живу\n4) живёте.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я часто  ... своему другу.\n\n1) помощь\n2) помогаю\n3) помогу\n4) помог",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Осенью в лесу очень … .\n\n1) красивый\n2) красавица\n3) красный\n4) красиво.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Зимой ... снег.\n\n1) идти\n2) идёт\n3) ходит\n4) едет.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Осенью ... дождь.\n\n1) идти\n2) идёт\n3) ходит\n4) едет.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Летом часто ... солнце.\n\n1) светит\n2) светить\n3) свети\n4) светят.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Алина Кабаева - гимнастка, она любит … .\n\n1) спорт\n2) спортсмен\n3) спортсменка\n4) спортивный.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Анна … в большой компании.\n\n1) работа\n2) работать\n3) работает\n4) работаю.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я ... домашнее задание.\n\n1) делаю\n2) делать\n3) делает\n4) делайте.",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Мы ... новые слова.\n\n1) учим\n2) учить\n3) учит\n4) учите.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Ольге очень … слушать современную популярную музыку,\n\n1) любит\n2) нравится\n3) хочет\n4) может.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Я часто ... в кафе с друзьями.\n\n1) делаю\n2) лежу\n3) стою\n4) хожу.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "В кафе мы обычно … чай.\n\n1) едим\n2) пьём\n3) смотрим\n4) пишем.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "Где ... остановка?\n\n1) ближний\n2) ближе\n3) ближайшая\n4) близко",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "На каникулах я поеду отдыхать в деревню ... бабушке.\n\n1) о\n2) у\n3) к\n4) в",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Это мой дедушка, он уже … .\n\n1) студент\n2) мужчина\n3) пенсионер\n4) ребёнок.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Раньше моя сестра часто … по телефону с подругой.\n\n1) разговаривала\n2) рассказывала\n3) сказала\n4) спрашивала",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Виктор очень ... поехать в Англию.\n\n1) может\n2) хочет\n3) умеет\n4) знает",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Виктор не … поехать в Англию, потому что у него нет денег.\n\n1) может\n2) хочет\n3) умеет\n4) знает",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "На праздник мы пригласили друзей ... Москвы.\n\n1) в\n2) из\n3) с\n4)к",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Вчера мы ... с другом в парке.\n\n1) встретился\n2) встретилась\n3) встретились\n4) встретились",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Если на улице дождь, нужно взять ... .\n\n1) шапку\n2) шарф\n3) зонт\n4) перчатки",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Сегодня хорошая ... .\n\n1) погода\n2) погоду\n3) погоде\n4) погодой",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Летом обычно очень ... .\n\n1) холодно\n2) тепло\n3) снежно\n4) ветрено.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Когда светит солнце, на улице ... .\n\n1) темно\n2) светло\n3) холодно\n4) страшно.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Осенью листья на деревьях ... .\n\n1) зеленые\n2) белые\n3) желтые\n4) синие.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "На лекции известный журналист рассказал ... Германии\n\n1) в\n2) на\n3) о\n4) из.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Я ... в университет.\n\n1) ходю\n2) ходить\n3) хожу\n4) ходит.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Мой любимый поэт - Анна Ахматова. Я очень люблю ... стихи.\n\n1) их\n2) его\n3) её\n4) ваши.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "В праздники люди любят ryлять … площади.\n\n1) в\n2) на\n3) о\n4) к.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Вчера мы … в парк.\n\n1) пошёл\n2) пошли\n3) идём\n4) ходим.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "В выходных он ... спортом.\n\n1) делает\n2) занимается\n3) работает\n4) играет.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Мой день рождения ... июле.\n\n1) в\n2) на\n3) о\4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Урок длится ... час.\n\n1) в\n2) на\n3) за\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Я встаю ... семь часов.\n\n1) в\n2) на\n3) о\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Мы учимся ... сентябре.\n\n1) в\n2) на\n3) о\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Пара началась ... 9 часов.\n\n1) в\n2) на\n3) о\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Концерт будет ... субботу.\n\n1) в\n2) на\n3) о\4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Они разговаривали ... час.\n\n1) в\n2) на\n3) за\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "… прошел мимо нас?\n\n1) Кто\n2) Что\n3) О ком\n4) У кого",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "Я живу ... большом городе.\n1) в\n2) на\n3) о\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "… тебя есть вопросы?\n\n1) Нет\n2) У\n3) Это\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Grammar",
            "task_content": "… здесь есть библиотека?\n\n1) Нет\n2) У\n3) Здесь\n4) —.",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… начнется пара?\n\n1) Когда\n2) Где\n3) Куда\n4)Кто",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… нам ждать?\n\n1) Какой\n2) Сколько\n3) Кто\n4) Что",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… тебя зовут?\n\n1) Как\n2) Сколько\n3) Что\n4) Кто",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… пройти до метро?\n1) Когда\n2) Что\n3) Кто\n\n4) Как",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… находится аптека?\n\n1) Где\n2) У кого\n3) Сколько\n4) Куда",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… у Вас болит?\n1) Кто\n2) Куда\n3) Что\n\n4) Во сколько",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Grammar",
            "task_content": "… мы встретимся?\n\n1) Во сколько\n2) Что\n3) Куда\n4) Откуда",
            "task_question": "Выберите верный вариант ответа из предложенных выше",
            "check_method": "multiple_choice",
            "task_score": 4,
            "answer": 1
        },
{
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Мой дедушка всегда читает газету утром и вечером, а телевизор смотрит только вечером.\n\nКогда дедушка смотрит телевизор?\n\n1) Утром\n2) Днём\n3) Вечером\n4) Никогда",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "У нас в семье четыре человека: папа, мама, брат и я. Папа работает, мама работает, брат учится, а я ещё маленький.\n\nКто не учится и не работает?\n\n1) Папа\n2)  Мама\n3)  Брат\n4) Автор",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 4
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "У меня есть друг. Его зовут Антон. Он живёт рядом с парком. У Антона есть собака. Её зовут Рекс. Рекс большой и добрый.\n\nКак зовут собаку?\n\n1) Антон\n2) Рекс\n3) Дима\n4) Тузик",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Анна и Мария — подруги. Анна любит музыку и поёт. Мария любит спорт и бегает каждый день.\n\nКто любит спорт?\n\n1) Анна\n2) Мария\n3) Обе\n4) Никто",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Сегодня холодно, и дети надели тёплые куртки. Завтра будет тепло.\n\nПочему дети надели куртки?\n\n1) Потому что сегодня холодно\n2) Потому что завтра будет тепло\n3) Потому что они любят куртки\n4) Потому что идёт дождь",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Летом всегда жарко, и мы ходим на пляж. Зимой мы носим тёплую одежду и катаемся на лыжах.\n\nЧто мы делаем зимой?\n\n1) Ходим на пляж\n2) Катаемся на лыжах\n3) Загораем\n4) Плаваем",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Моя сестра хорошо рисует, но плохо поёт. А я, наоборот, хорошо пою, но плохо рисую.\n\nЧто сестра делает лучше?\n\n1) Рисует\n2) Поёт\n3) Танцует\n4) Читает",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "В субботу мы идём в кино, а в воскресенье — к бабушке.\n\nКуда мы идём в воскресенье?\n\n1) В парк\n2) В кино\n3) К бабушке\n4) В магазин",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Сегодня пятница. Завтра будет суббота.\n\nВопрос: Какой день будет завтра?\n\n1) четверг\n2) пятница\n3) суббота\n4) воскресенье",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Мой день рождения 10 января. Сегодня 9 января.\n\nВопрос: Когда день рождения?\n\n1)завтра\n2) послезавтра\n3) вчера\n4) сегодня",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "В магазине мама купила хлеб, молоко и сыр. Я попросил ещё яблоки, но их не было.\n\nЧто мама не купила?\n\n1) Хлеб\n2) Молоко\n3) Яблоки\n4) Сыр",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Вы в автобусе. Водитель говорит: «Проездной билет, пожалуйста!»\n\nВопрос: Что нужно показать?\n\n1) Паспорт\n2) Проездной билет\n3) Деньги\n4) Телефон",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Прочтите надпись на двери: «Не входить! Идёт совещание».",
            "task_question": "Что это значит?\n\n1) Можно заходить, если тихо\n2) Заходить нельзя\n3) Совещание уже закончилось\n4) Здесь всегда можно зайти",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Прочтите расписание на дверях магазина: «Работаем с 9:00 до 21:00. Воскресенье — выходной».",
            "task_question": " Когда магазин закрыт?\n\n1) В субботу\n2) В понедельник\n3) В воскресенье\n4) В среду",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Прочтите ценник в магазине: «Хлеб — 50 рублей».",
            "task_question": "Сколько стоит хлеб?\n\n1) 5 рублей\n2) 15 рублей\n3) 50 рублей\n4) 55 рублей",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Прочтите указатель в городе: «Станция метро → 500 метров».",
            "task_question": "Что показывает этот указатель?\n\n1) Здесь есть метро\n2) До метро далеко, нужно ехать на автобусе\n3) До метро идти 5 минут пешком\n4) Метро закрыто",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "7.00 – Утренняя гимнастика\n7.30 – Новости\n8.00 – Мультфильмы",
            "task_question": "Где можно прочитать?\n\n1) в газете «Программа ТВ»\n2) в учебнике\n3) в библиотеке",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Уважаемые пассажиры! Следующая станция — улица Ленина.",
            "task_question": "Где можно услышать?\n\n1) в автобусе\n2) в аптеке\n3) в школе",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Скидки на все товары — 50%!",
            "task_question": "Где можно увидеть?\n\n1) в магазине\n2) в поликлинике\n3) в банке",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "Соблюдайте правила дорожного движения!",
            "task_question": "Где можно увидеть?\n\n1) на улице, на плакате\n2) в ресторане\n3) на кухне",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Reading",
            "task_content": "В этом зале проходит лекция по истории.",
            "task_question": "Где можно увидеть?\n\n1) в университете\n2) в магазине\n3) в парке",
            "check_method": "multiple_choice",
            "task_score": 3,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "В моей комнате есть кровать, стол и стул. На столе стоит компьютер. На стене висит карта мира.\n\nЧего нет в комнате у героя?\n\n1) Телевизор\n2) Стол\n3) Стул\n4) Кровать",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Привет! Меня зовут Андрей! Мне 12 лет. У меня много друзей. Моего лучшего друга зовут Паша. Мы одного возраста и учимся в одном классе.\n\nСколько Паше лет?\n\n1) Двенадцать\n2) Десять\n3) Девять\n4) Пять",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Олег любит смотреть футбол, но сам играет редко. Зато он часто бегает в парке.\n\nЧто Олег делает чаще?\n\n1) Играет в футболь\n2) Смотрит телевизор\n3) Бегает в паркe\n4) Спит",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Сегодня утром шёл дождь, поэтому я взял зонт. Сейчас дождь закончился, и светит солнце.\n\nПочему я взял зонт?\n\n1) Потому что светит солнце\n2) Потому что шёл дождь\n3) Потому что холодно\n4) Потому что я его люблю",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Аня: «Чем ты занимаешься в свободное время?»\nПетя: «Я люблю смотреть сериалы и сидеть в интернете.»\n\nЧем Петя любит заниматься в свободное время?\n\n1) Сидеть в интернете\n2) Гулять в лесу\n3) Читать детективы\n4) Играть в шахматы",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Сейчас 3 часа. Урок начинается в 3 часа.\n\nВопрос: Во сколько начинается урок?\n\n1) в два часа\n2) в три часа\n3) в четыре часа\n4) в пять часов",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Прочтите инструкцию: «Принимать по 1 таблетке 2 раза в день после еды».",
            "task_question": " Сколько таблеток нужно принять за один день?\n\n1) Одну\n2) Две\n3) Четыре\n4) Десять",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Прочтите вывеску в кафе: «Свободных мест нет».",
            "task_question": " Что это значит?\n\n1) В кафе можно зайти и поесть\n2) Места есть, но нужно ждать\n3) Мест нет, нужно ждать или уйти\n4) Кафе закрыто навсегда",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "Сегодня Анна отмечает день рождения. …",
            "task_question": "Продолжи высказывание:\n\n1) Давай подарим ей цветы!\n2) Она любит футбол.\n3) Я читаю книгу.",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Reading",
            "task_content": "В магазине большая очередь. …",
            "task_question": "Продолжи высказывание:\n\n1) Давай купим продукты завтра.\n2) Пошли в аптеку.\n3) Сегодня хороший день.",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "После завтрака мы собираемся и идем в школу. Моя сестра учится в пятом классе, а я – во втором. Мы любим учиться и играть с друзьями.\n\nКто такая Аня?\n\n1) Младшая сестра\n2) Старшая сестра\n3) Сестра-близнец\n4) Бабушка",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Мы обычно играем в футбол с другими ребятами после школы. Мы всегда играем в одной команде. Мой друг, Паша, очень любит спорт и мечтает стать тренером, когда вырастет. Иногда мы идем ко мне домой после футбола и делаем вместе домашнюю работу. Паша всегда объясняет мне сложные задачи, потому что учится лучше меня, особенно по математике.\n\nВыбери неверное утверждение:\n\n1) Друзья часто играют в баскетбол\n2) Паша хочет стать тренером\n3) Паша учится хорошо",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Сегодня солнечно. Дети играют в парке. Мама говорит: «Надень кепку!»\n\nПочему нужно надеть кепку?\n\n1) Потому что холодно\n2) Потому что идёт дождь\n3) Потому что светит солнце\n4) Потому что ветер",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Моя преподавательница встает в семь утра и едет в университет на автомобиле. Когда она приезжает на работу, она заходит в аудиторию и снимает пальто.\n\nКак преподавательница добирается в университет?\n\n1) На машине\n2) На автобусе\n3) Пешком\n4) На метро",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Когда Татьяна Петровна приходит домой, она убирается, пылесосит, готовит ужин, купает детей и читает им сказки на ночь. Николай помогает ей по дому. Когда дети ложатся спать, она садится проверять домашние задания.\n\nЧто делает Татьяна Петровна, когда дети ложатся спать?\n\n1) Проверяет домашние задания\n2) Идет спать\n3) Слушает новости\n4) Убирает квартиру",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Петя: «Что тебе нравится делать в свободное время?\nАня: «Мне нравится встречаться с друзьями.»\nПетя: «Куда вы обычно ходите?»\nАня: «Обычно мы встречаемся в кафе, но на выходных ходим в клуб. Иногда я приглашаю их к себе, потому что люблю готовить.»\n\nЧто любит делать Аня?\n\n1) Отдыхать на природе\n2) Готовить\n3) Водить машину\n4) Играть на пианино",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Сегодня воскресенье. Сегодня мы всей семьей испекли пирог с яблоками. Пока пирог был в духовке, мы играли в настольную игру. Запах был такой вкусный! Наконец, пирог испёкся. Мы сели пить чай.\n\nЧто мы НЕ делали на эти выходных?\n\n1) Испекли пирог\n2) Пили чай\n3) Купили пиццу\n4) Играли в настольную/ игру",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Урок длится 45 минут. Перемена длится пятнадцать минут.\n\nВопрос: Сколько длится перемена?\n\n1) 45 минут\n2) 30 минут\n3) 15 минут\n4)10 минут",
            "task_question": "Выберите верный вариант ответа из предложенных ниже",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Прочтите надпись на двери в спортивный зал: «Вход ТОЛЬКО в сменной обуви!»",
            "task_question": "Что значит эта надпись?\n\n1) Надо переобуть обувь\n2) Надо снять обувь\n3) Входить можно только в носках",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Прочтите объявление в автобусе: «Уступайте места пожилым людям и пассажирам с детьми».",
            "task_question": "Кому нужно уступать место?\n\n1) Только пожилым людям\n2) Только пассажирам с детьми\n3) Пожилым людям и пассажирам с детьми\n4) Всем пассажирам",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Прочтите правило в библиотеке: «В зале тишины разговаривать запрещено».",
            "task_question": " Где нельзя разговаривать?\n\n1) В библиотеке\n2) В парке\n3) В зале тишины в библиотеке\n4) Дома",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Мне очень холодно. …",
            "task_question": "Продолжи высказывание:\n\n1)Надень куртку!\n2) Сегодня жарко.\n3) Я хочу есть.",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Я плохо себя чувствую. …",
            "task_question": "Продолжи высказывание:\n\n1) Выпей лекарство!\n2) Пойдём гулять!\n3) Посмотри фильм!",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 1
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Я не люблю вставать рано. …",
            "task_question": "Продолжи высказывание:\n\n1) Я всегда просыпаюсь в 6 утра.\n2) Я люблю спать долго.\n3) Я смотрю телевизор.",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Внимание! Лифт временно не работает.",
            "task_question": "Где можно увидеть?\n\n1)в парке\n2) в подъезде дома\n3) в автобусе",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Reading",
            "task_content": "Осторожно! Скользкий пол.",
            "task_question": "Где можно увидеть?\n\n1) у друга дома\n2) в автобусе\n3) в супермаркете",
            "check_method": "multiple_choice",
            "task_score": 7,
            "answer": 3
        },
{
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Как вы себя чувствуете?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Скажите, пожалуйста, вы говорите по-английски?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сколько вам лет?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Откуда вы?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы студент или работаете?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Как зовут вашу маму?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Как зовут ваших родителей?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Кто ваш лучший друг или подруга?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «У вас много друзей?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Ваши друзья живут далеко от вас?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «На каком языке говорит ваш лучший друг?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сегодня солнечно или идёт дождь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какая сегодня погода?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «В вашем городе часто снег зимой?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы любите жару?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Где вы учитесь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы учитесь или работаете?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вам нравится ваш университет?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы любите читать книги?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы любите смотреть фильмы или сериалы?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы любите ездить на поезде или на автобусе?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вы в автобусе. Слышите объявление:\n\n— Следующая остановка — «Центральный рынок».\n\n Вопрос: Куда вы приедете на следующей остановке?",
            "task_question": "Ваша задача: Назвать место.\n\nОтветьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Вы покупаете билет в кино. Кассир спрашивает:\n\n — Один билет на «Мстители» на 19:00?\n\nВопрос: На какой фильм и во сколько билет?",
            "task_question": "Ваша задача: Повторить ключевую информацию (фильм и время).\n\nОтветьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Ситуация: Вы в магазине. Продавец спрашивает:\n\n — Вам пакет нужен?",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Speaking",
            "task_content": "Ситуация: Вы спросили, где банк. Прохожий ответил:\n\n— Банк там, рядом с аптекой.",
            "task_question": "Вопрос: Где банк?\n\nОтветьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 5
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задал вопрос друг: «Где вы обычно отдыхаете летом?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Где вы живёте?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сколько у вас братьев и сестёр?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Есть ли у вас домашние животные?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сколько человек в вашей семье?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Где живёт ваша семья?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы часто видитесь с семьёй?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Ваш друг тоже изучает русский язык?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Как часто вы звоните друзьям?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы смотрите прогноз погоды?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы берёте зонт, если по прогнозу дождь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Во сколько начинается ваш учебный день?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Вы устаёте после учебы?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какое у вас хобби?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какой сегодня день недели?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Когда у вас день рождения?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «В каком месяце вы родились?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сколько дней в неделе?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Ситуация: Вы в кафе. Официант спрашивает:\n\n— Что будете пить?",
            "task_question": "Ваша задача: Назвать напиток.\n\nОтветьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «О чём вы мечтаете?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Кто в вашей семье самый старший?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Что вы любите делать вместе с семьёй?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Где вы познакомились с вашим лучшим другом?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Как вы проводите время с друзьями?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Что вам нравится в вашем друге?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какая ваша любимая погода?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Что вы делаете, когда идёт дождь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какая погода была вчера?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «На кого вы учитесь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Кем вы хотите работать?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «С кем вы обычно проводите выходные?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Где вы обычно отдыхаете летом?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Который сейчас час?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Какое сегодня число?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Во сколько вы обычно просыпаетесь?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вам задали вопрос: «Сколько времени вы тратите на дорогу до работы/университета?»",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вы звоните в такси. Диспетчер спрашивает:\n\n— Какой ваш адрес? Откуда вас забрать?\n\nВаша задача: Назвать свой адрес или любое место в городе.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Вы встречаете друга в аэропорту. Он звонит и говорит:\n\n— Я прилетел! Я выхожу к выходу номер 3.\n\nЗадание: Ответьте другу, что скоро подойдете, и скажите, где вы находитесь (можете придумать номер выхода).",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Попросите преподавателя объяснить тему.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Поздоровайтесь с одногруппником и представьтесь (имя, фамилия, откуда вы, сколько вам лет)",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Попросите у одногруппника помочь с домашним заданием.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Middle",
            "type_task": "Speaking",
            "task_content": "Вы в магазине. Скажите, что вы хотите купить молоко и хлеб.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Скажите врачу, что у вас болит горло.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Senior",
            "type_task": "Speaking",
            "task_content": "Скажите врачу, сколько дней вы плохо себя чувствуете.",
            "task_question": "Ответьте (отправьте голосовое сообщение).",
            "check_method": "open_question_speaking",
            "task_score": 10
        },
{
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Напиши однокурснику и спроси, во сколько начинаются пары завтра. Не забудь приветствие!",
            "task_question": "Вам нужно написать сообщение. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 8
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Напишите соседу и попросите сделать тише музыку.",
            "task_question": "Вам нужно написать сообщение. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Извинись перед соседом за шум с твоей стороны.",
            "task_question": "Вам нужно написать сообщение. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Напишите сообщение другу, попросите друга купить яблоки.",
            "task_question": "Вам нужно написать сообщение. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 7
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Ваш друг звонит вам и говорит:\n– Привет! Ты свободен завтра вечером?",
            "task_question": "Вам нужно написать сообщение. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 8
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "У вас болит горло, и Вы пришли к врачу. Врач спрашивает:\n– Что у вас болит?",
            "task_question": "Вам нужно написать сообщение и ответить на вопрос. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "У вас день рождения. Напишите другу приглашение (когда, где, во сколько).",
            "task_question": "Вам нужно написать сообщение и ответить на вопрос. Объем: 1-2 предложения.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Опишите свою семью: кто есть, как зовут.",
            "task_question": "Вам нужно написать короткий текст с расскзаом о своей семье. Объем: 2-4 предложения.",
            "check_method": "open_question_writing",
            "task_score": 8
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Напишите короткий текст: где вы учитесь, какие языки изучаете.",
            "task_question": "Напишите короткий текст. Объем: 2-4 предложения.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Опишите свой обычный день (что вы делаете утром, днём, вечером).",
            "task_question": "Напишите короткий текст. Объем: 3-5 предложений.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Объясните другу, как пройти в магазин от вашего дома.",
            "task_question": "Напишите короткий текст. Объем: 2-3 предложениz.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Напишите список покупок в магазине.",
            "task_question": "Напишите список покупок. Объем: 5-6 слов",
            "check_method": "open_question_writing",
            "task_score": 10
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Writing",
            "task_content": "Опишите ваш завтрак (что вы обычно едите и пьёте).",
            "task_question": "Напишите небольшой текст. Объем: 1-3 предложения.",
            "check_method": "open_question_writing",
            "task_score": 10
        },
{
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Listening",
            "task_content": "Мой любимый предмет в школе — история, а не математика.",
            "task_question": "Вопрос: Какой его любимый предмет?\n\n1) Математика\n2) История\n3) География\n\nНапиши ТОЛЬКО номер ответа!",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        },
        {
            "level_score": 1,
            "level_name": "A1",
            "module_name": "Easy",
            "type_task": "Listening",
            "task_content": "Мой любимый цвет — синий. У меня есть сумка этого цвета.",
            "task_question": "Какой любимый цвет рассказчика?\n\n1) Красный\n2) Синий\n3) Зелёный\n\nНапиши ТОЛЬКО цифру ответа!",
            "check_method": "multiple_choice",
            "task_score": 5,
            "answer": 2
        }
    ]
}



